// tienda-react/src/LoginComponent.js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import './LoginComponent.css';
import DashboardComponent from './DashboardComponent.js';
import User from './model/User';
import Session from './model/Session';
import { Button } from 'react-bootstrap';

class LoginComponent extends Component {

  constructor(props) {
    super(props);

    this.state = {
      username: '',
      password: '',
      validUsername: true,
      validPassword: true,
      validLogin: true
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleChange(event) {
    if (event.target.id === 'username') {
      this.setState({
        username: event.target.value
      });
    } else if (event.target.id === 'password') {
      this.setState({
        password: event.target.value
      });
    }
  }

  handleSubmit(event) {
    var validForm = true;
    if (this.state.username === '') {
      this.setState({
        validUsername: false
      });
      validForm = false;
    } else {
      this.setState({
        validUsername: true
      });
    }

    if (this.state.password === '') {
      this.setState({
        validPassword: false
      });
      validForm = false;
    } else {
      this.setState({
        validPassword: true
      });
    }

    if (validForm) {
      this.performLogin(this.state.username, this.state.password);
    }

    event.preventDefault();
  }

  performLogin(username, password) {
    var headers = {
      'Authorization': 'Basic a2lkX1NraG5KdmxOUzoxNjMwYjJlMGNmYTE0OTYyODNiYjdlNTc1ZjBjOThmMg==',
      'X-Kinvey-API-Version': '3',
      'Content-Type': 'application/json'
    };
    var credentials = {
      username: username,
      password: password
    };
    var body = JSON.stringify(credentials);

    fetch("https://baas.kinvey.com/user/kid_SkhnJvlNS/login", {
      method: 'post',
      headers: headers,
      body: body
    }).then(response => response.json())
      .then(responseJson => {
        console.log(responseJson);
        if (responseJson.error) {
          this.setState({ 
            validLogin: false 
          })
        } else {
          var user = new User()
          user.username = responseJson.username;
          user.token=responseJson._kmd.authtoken;
          var session = Session.getInstance();
          session.user = user;
          ReactDOM.render(
            <DashboardComponent />,
            document.getElementById('root')
          );
        }
      })
      .catch(error => {
        console.error(error);
      })
  }

  render() {
    var { Grid, Row, Col, FormGroup, FormControl, ControlLabel, Alert } = require('react-bootstrap');
    return (
      <div className="fondo">
        <Grid>
          <Row className="white-text justify-content-center">
            <Col lg={6} xsOffset={3}>
              <h1 className="text-center">Inicia Sesión</h1>
              <form className="form" onSubmit={this.handleSubmit}>
                <FormGroup>
                  <ControlLabel htmlFor="username">Nombre de usuario</ControlLabel>
                  <FormControl id="username" type="text" placeholder="Usuario:" onChange={this.handleChange} value={this.state.username} />
                  {!this.state.validUsername &&
                    <ControlLabel className="error">Debes ingresar un nombre de usuario Válido</ControlLabel>
                  }
                </FormGroup>

                <FormGroup>
                  <ControlLabel htmlFor="password">Contraseña</ControlLabel>
                  <FormControl id="password" type="password" placeholder="Contraseña:" onChange={this.handleChange} value={this.state.password} />
                  {!this.state.validPassword &&
                    <ControlLabel className="error">Debes introducir una contraseña válida</ControlLabel>
                  }
                </FormGroup>

                {!this.state.validLogin &&
                  <Alert bsStyle="warning">
                    <span className="glyphicon glyphicon-ban-circle"></span> El usuario o contraseña no son correctos!
                    </Alert>
                }

                <FormGroup>
                  <Button bsStyle="success" type="submit" >Ingresar</Button>
                </FormGroup>
              </form>
            </Col>
          </Row>
        </Grid>
      </div>
    );
  }
}
export default LoginComponent;

// tienda-angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from '../model/User';
import { LoginService } from '../login.service'
import { SessionService } from '../session.service'
import { ShoppingCartService } from '../shopping-cart.service';
import { Router } from '@angular/router'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  title = 'Login';

  user = {
    username: '',
    password: ''
  };

  validUsername = true
  validPassword = true

  validLogin = true

  constructor(private shoppingCartService: ShoppingCartService, private loginService: LoginService, private sessionService: SessionService, private router: Router) { }

  ngOnInit() {

    this.shoppingCartService.resetShoppingCart();
  }

  submitForm(form) {

    let validForm = true

    if (this.user.username == "") {
      this.validUsername = false
      validForm = false
    } else {
      this.validUsername = true
    }

    if (this.user.password == "") {
      this.validPassword = false
      validForm = false
    } else {
      this.validPassword = true
    }

    if (validForm) {

      this.performLogin(this.user.username, this.user.password);
    }
  }

  performLogin(username: string, password: string) {

    this.loginService.performLogin(username, password).subscribe(
      data => {

      let user: User = {
        username: data.username,
        token: data._kmd.authtoken
      }

      this.sessionService.user = user;

      this.router.navigate(['./dashboard']);
    },

    error => {

      this.validLogin = false;
    })
  }
}

<div class="container-fluid">

  <div class="row white-text justify-content-center">
  
    <div class="col-4 align-self-center">
  
      <h1 class="text-center">Iniciar Sesión</h1>
  
        <form class="form" (ngSubmit)="submitForm(f)" #f="ngForm">
          <div class="form-group">
            <label for="username"> Usuario:</label>
            <input class="form-control" placeholder="Usuario" type="text" [(ngModel)]="user.username" name="username" required>
            <label *ngIf="!validUsername" class="error">Introdusca un nombre de usuario válido</label>
          </div>
  
          <div class="form-group">
            <label for="password"> Contraseña:</label>
            <input class="form-control" placeholder="Contraseña" type="password" [(ngModel)]="user.password" name="password" required>
            <label *ngIf="!validPassword" class="error">Introdusca una contraseña válida</label>
          </div>
  
          <div class="alert alert-warning" *ngIf="!validLogin">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>El usuario o contraseña no son correctos!!!
          </div>
  
          <div class="form-group text-center">
            <button type="submit" class="btn btn-success" name="button">Ingresar</button>
          </div>
        </form>
  
      </div>
    </div>
 </div>
