// tienda-react/src/ShoppingCartComponent.js
import React, { Component } from 'react';
import ShoppingCartItemComponent from './ShoppingCartItemComponent.js';
import ShoppingCartService from './service/ShoppingCartService';
import { Grid, Jumbotron, Row, Col, Button } from 'react-bootstrap';
import ReactDOM from 'react-dom';
import ProductCatalogComponent from './ProductCatalogComponent';

class ShoppingCartComponent extends Component {

    constructor(props) {
        super(props);

        this.state = {
            service: ShoppingCartService.getInstance()
        }
        this.pay = this.pay.bind(this);
    }

    cancel() {

        ReactDOM.render(<ProductCatalogComponent />,
            document.getElementById('content'));
    }

    pay() {
        this.state.service.payShoppingCart();
    }

    render() {
        var body = [];
        this.state.service.shoppingCartItems.forEach(element => {
            body.push(<Col lg={12} key={element.id}><ShoppingCartItemComponent item={element} /></Col>);
        });

        return (
            <Grid>
                <br />
                <Jumbotron>
                    <Grid>
                        <Row>
                            <Col>
                                <h1>Carrito de compras</h1>
                            </Col>
                        </Row>

                        <Row>
                            <Col lg={6}>
                                <Grid>
                                    {body}
                                </Grid>
                            </Col>

                            <Col lg={6}>
                                <h1>Total: {this.state.service.total()}</h1>
                                <Button bsStyle="danger" onClick={this.cancel}>Cancelar</Button>
                                <Button bsStyle="success" onClick={this.pay}>Pagar</Button>
                            </Col>
                        </Row>
                    </Grid>
                </Jumbotron>
            </Grid>
        );
    }
}
export default ShoppingCartComponent;

// tienda-angular/src/app/shopping-cart/shopping-cart.component.ts
import { Component, OnInit } from '@angular/core';
import { ShoppingCartService } from '../shopping-cart.service';
import { SessionService } from '../session.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-shopping-cart',
  templateUrl: './shopping-cart.component.html',
  styleUrls: ['./shopping-cart.component.css']
})
export class ShoppingCartComponent implements OnInit {

  title = "Carrito de compras"

  constructor(private router: Router, private shoppingCartService: ShoppingCartService, private sessionService: SessionService) { }

  ngOnInit() {

    if (this.sessionService.user == null) {

      this.router.navigate(['/login']);
    }
  }

  pay() {

    this.shoppingCartService.payShoppingCart();

  }
}
<div class="background">

  <div class="container">
  
    <app-header></app-header>
  
      <br>
  
    <div class="jumbotron">
  
      <div class="container">
        <div class="row">
          <div class="col">
            <h1>{{title}}</h1>
          </div>
        </div>
  
        <div class="row">
  
          <div class="col-6">
            <div class="container">
              <div class="" *ngFor="let item of shoppingCartService.shoppingCartItems">
  
                <app-shopping-cart-item [item]="item"></app-shopping-cart-item>
  
              </div>
            </div>
          </div>
  
          <div class="col-6">

            <h1>Total: {{shoppingCartService.total() | currency}}</h1>
  
            <a routerLink="/dashboard"> <button type="button" class="btn btn-danger">Cancelar</button> </a>
            <button type="button" class="btn btn-success" (click)=pay()>Pagar</button>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>
