// tienda-angular/src/app/product-detail/product-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Router } from '@angular/router';
import { ProductService } from '../product.service';
import { Product } from '../model/Product';
import { SessionService } from '../session.service';

@Component({
  selector: 'app-product-detail',
  templateUrl: './product-detail.component.html',
  styleUrls: ['./product-detail.component.css']
})
export class ProductDetailComponent implements OnInit {

  product: Product;

  constructor(private router: Router, private route: ActivatedRoute, private productService: ProductService, 
private location: Location, private sessionService: SessionService) { }

  ngOnInit() {

    if (this.sessionService.user == null) {
      this.router.navigate(['/login']);

    } else {
      let id = this.route.snapshot.paramMap.get('id');

      this.getProductDetail(id);
    }
  }

  getProductDetail(id: string) {

    this.productService.performGetProductById(this.sessionService.user.token, id).subscribe(
      data => {

        this.product = {
          "id": data._id,
          "name": data.name,
          "price": data.price,
          "image": data.image,
          "stock": data.stock
        }
      },
      error => {

        alert("Error al consultar el detalle del producto");

      }
    )
  }

  goBack() {
    this.location.back();
  }
}
<div class="background">

  <div class="container">
    <app-header></app-header>
  
    <br>
  
    <div class="jumbotron">
      <div class="container">
  
        <div class="row">
          <div class="col">
            <h1>{{product.name}}</h1>
          </div>
        </div>
  
        <div class="row">
          <div class="col">
            <img src="../../assets/{{product.image}}" alt="image {{product.name}}" height="250px" />
          </div>
  
          <div class="col">
            <h4>{{product.name}}</h4>
              <h6><strong>Precio:</strong> {{product.price | currency}}</h6>
              <h6> <strong> Unidades disponibles: </strong> {{product.stock}}</h6>
          </div>
        </div>
  
        <div class="row">
          <div class="col-2">
            <button type="button" class="badge badge-primary" (click)="goBack()"><strong>Atrás</strong></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// tienda-react/src/ProductDetailComponent.js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import ProductCatalogComponent from './ProductCatalogComponent.js';
import { Grid, Jumbotron, Row, Col, Button } from 'react-bootstrap';

class ProductDetailComponent extends Component {
    constructor(props) {
        super(props);
        this.state = {
            product: props.product
        }
        this.goBack = this.goBack.bind(this);
    }

    goBack() {
        ReactDOM.render(
            <ProductCatalogComponent />,
            document.getElementById('content')
        );
    }

    render() {
        var img = require('./img/' + this.state.product.image);
        return (
            <Grid>
                <Jumbotron>
                    <Grid>
                        <Row>
                            <Col>
                                <h1>{this.state.product.name}</h1>
                            </Col>
                        </Row>

                        <Row>
                            <Col lg={6}>
                                <img src={img} alt={img} height="300px" />
                            </Col>

                            <Col lg={6}>
                                <h4>{this.state.product.name}</h4>
                                <h6> <strong> Precio:</strong> {this.state.product.price}</h6>
                                <h6> <strong> Unidades disponibles: </strong> {this.state.product.stock}</h6>
                            </Col>
                        </Row>

                        <Row>
                            <Col lg={2}>
                                <Button bsStyle="default" onClick={this.goBack} >Atrás</Button>
                            </Col>
                        </Row>
                    </Grid>
                </Jumbotron>
            </Grid>
        );
    }
}
export default ProductDetailComponent;
