// tienda-angular/src/app/shopping-cart-item/shopping-cart-item.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ShoppingCartItem } from '../model/ShoppingCartItem';


@Component({
  selector: 'app-shopping-cart-item',
  templateUrl: './shopping-cart-item.component.html',
  styleUrls: ['./shopping-cart-item.component.css']
})
export class ShoppingCartItemComponent implements OnInit {

  @Input()
  item: ShoppingCartItem;

  constructor() { }

  ngOnInit() {

  }

}
<div class="bordered">

  <div class="row">
    <div class="col-3">
      <img src="../../assets/{{item.product.image}}" alt="image {{item.product.name}}" height="50" width="100" />
    </div>
  
    <div class="col-8">
      <h4>{{item.product.name}}</h4>
      <h6><strong>Unidades:</strong> {{item.quantity}}</h6>
    </div>
  </div>
  
  <div class="row">
    <div class="col">
      <h6> <strong> Subtotal: </strong> {{item.subtotal() | currency}}</h6>
    </div>
  </div>
</div>

// tienda-react/src/ShoppingCartItemComponent.js
import React, { Component } from 'react';
import { Row, Col } from 'react-bootstrap';
import './ShoppingCartItemComponent.css';

class ShoppingCartItemComponent extends Component {

    render() {
        var img = require('./img/' + this.props.item.product.image);
        return (
            <div className="itemBordered">
                <Row>
                    <Col lg={3}>
                        <img src={img} alt={img} height="50" width="100" />
                    </Col>
                    <Col lg={1} />
                    <Col lg={7}>
                        <h4> {this.props.item.product.name}</h4>
                        <h6> <strong>Unidades:</strong> {this.props.item.quantity}</h6>
                    </Col>
                </Row>

                <Row>
                    <Col>
                        <h6> <strong> Subtotal: </strong> {this.props.item.subtotal()}</h6>
                    </Col>
                </Row>
            </div>
        );
    }
}
export default ShoppingCartItemComponent;
